/* Caffetteria Mazzetti — interactive cookbook data + i18n */
const I18N = {
  it: {
    open:"Apri il ricettario", search:"Cerca una ricetta…", all:"Tutto l'anno",
    fav:"Preferiti", shop:"Spesa", notes:"Note", about:"Il caffè",
    ing:"Ingredienti", prep:"Preparazione", cook:"Cucina ora",
    addShop:"Aggiungi alla spesa", added:"In lista",
    next:"Avanti", prev:"Indietro", close:"Chiudi", done:"Fatto",
    emptyFav:"Nessun preferito ancora. Tocca il cuore su una ricetta.",
    emptyShop:"La lista della spesa è vuota.",
    shopTitle:"Lista della spesa", clearShop:"Svuota",
    notePh:"I tuoi appunti — dosi, vini, chi era a tavola…",
    save:"Salvato in questo browser",
    steps:"Passi", timer:"Timer",
    dedicaTitle:"Dedica",
    aboutBody:"La Caffetteria Mazzetti è in Corso Alfieri 357, all’ingresso dei Giardini Alganon, Asti. Cucina piemontese, caffè, vini del territorio. Questo quaderno segue i mesi come si cucina in famiglia.",
    addr:"Corso Alfieri 357, 14100 Asti Italia",
    illu:"Illustrazioni: Rebecca Valente",
    print:"Stampa", share:"Copia link",
    results:"ricette", noResults:"Nessuna ricetta trovata.",
    INVERNO:"Inverno", PRIMAVERA:"Primavera", ESTATE:"Estate", AUTUNNO:"Autunno",
    GENNAIO:"Gennaio", FEBBRAIO:"Febbraio", MARZO:"Marzo", APRILE:"Aprile",
    MAGGIO:"Maggio", GIUGNO:"Giugno", LUGLIO:"Luglio", AGOSTO:"Agosto",
    SETTEMBRE:"Settembre", OTTOBRE:"Ottobre", NOVEMBRE:"Novembre", DICEMBRE:"Dicembre",
    primo:"Primi", secondo:"Secondi", dolce:"Dolci", antipasto:"Antipasti", conserve:"Conserve",
    d:["Questo caffè è dedicato ai sognatori,","a chi si è ammalato di meraviglia,","a chi sospira nel vento,","a chi guarda la luna e si emoziona,","a chi accarezza il mondo,","a chi si è smarrito e poi si è ritrovato,","alle grandi anime,","ai sorrisi fatti di nascosto,","alla gente che sussurra,","alle nuvole colpite dal vento,","ai temporali, al sole,","alle persone che si vogliono bene senza saperlo,","alla primavera,","al giorno della tua nascita,","alla mia mamma e anche alla tua.","Dedicato a te, a me."]
  },
  en: {
    open:"Open the cookbook", search:"Search a recipe…", all:"All year",
    fav:"Favourites", shop:"Shop", notes:"Notes", about:"The café",
    ing:"Ingredients", prep:"Method", cook:"Cook now",
    addShop:"Add to shopping list", added:"On the list",
    next:"Next", prev:"Back", close:"Close", done:"Done",
    emptyFav:"No favourites yet. Tap the heart on a recipe.",
    emptyShop:"The shopping list is empty.",
    shopTitle:"Shopping list", clearShop:"Clear",
    notePh:"Your notes — quantities, wines, who sat at the table…",
    save:"Saved in this browser",
    steps:"Steps", timer:"Timer",
    dedicaTitle:"Dedication",
    aboutBody:"Caffetteria Mazzetti is at Corso Alfieri 357, by the Giardini Alganon, Asti. Piedmontese cooking, coffee, local wines. This booklet follows the months the way a family cooks.",
    addr:"Corso Alfieri 357, 14100 Asti, Italy",
    illu:"Illustrations: Rebecca Valente",
    print:"Print", share:"Copy link",
    results:"recipes", noResults:"No recipes found.",
    INVERNO:"Winter", PRIMAVERA:"Spring", ESTATE:"Summer", AUTUNNO:"Autumn",
    GENNAIO:"January", FEBBRAIO:"February", MARZO:"March", APRILE:"April",
    MAGGIO:"May", GIUGNO:"June", LUGLIO:"July", AGOSTO:"August",
    SETTEMBRE:"September", OTTOBRE:"October", NOVEMBRE:"November", DICEMBRE:"December",
    primo:"Pasta & first", secondo:"Mains", dolce:"Sweets", antipasto:"Starters", conserve:"Preserves",
    d:["This coffee is dedicated to the dreamers,","to those who fell ill with wonder,","to those who sigh into the wind,","to those who look at the moon and feel it,","to those who caress the world,","to those who got lost and found themselves again,","to the great souls,","to smiles made in secret,","to people who whisper,","to clouds struck by the wind,","to storms, to the sun,","to people who love each other without knowing it,","to spring,","to the day you were born,","to my mother, and to yours too.","Dedicated to you, to me."]
  },
  sv: {
    open:"Öppna kokboken", search:"Sök en recept…", all:"Hela året",
    fav:"Favoriter", shop:"Inköp", notes:"Anteckningar", about:"Caféet",
    ing:"Ingredienser", prep:"Tillagning", cook:"Laga nu",
    addShop:"Lägg i inköpslistan", added:"I listan",
    next:"Nästa", prev:"Tillbaka", close:"Stäng", done:"Klar",
    emptyFav:"Inga favoriter ännu. Tryck på hjärtat på ett recept.",
    emptyShop:"Inköpslistan är tom.",
    shopTitle:"Inköpslista", clearShop:"Töm",
    notePh:"Dina anteckningar — mängder, viner, vilka som satt vid bordet…",
    save:"Sparat i den här webbläsaren",
    steps:"Steg", timer:"Timer",
    dedicaTitle:"Tillägnan",
    aboutBody:"Caffetteria Mazzetti ligger på Corso Alfieri 357 vid Giardini Alganon i Asti. Piemontesisk mat, kaffe, lokala viner. Häftet följer månaderna som man lagar mat i familjen.",
    addr:"Corso Alfieri 357, 14100 Asti, Italien",
    illu:"Illustrationer: Rebecca Valente",
    print:"Skriv ut", share:"Kopiera länk",
    results:"recept", noResults:"Inga recept hittades.",
    INVERNO:"Vinter", PRIMAVERA:"Vår", ESTATE:"Sommar", AUTUNNO:"Höst",
    GENNAIO:"Januari", FEBBRAIO:"Februari", MARZO:"Mars", APRILE:"April",
    MAGGIO:"Maj", GIUGNO:"Juni", LUGLIO:"Juli", AGOSTO:"Augusti",
    SETTEMBRE:"September", OTTOBRE:"Oktober", NOVEMBRE:"November", DICEMBRE:"December",
    primo:"Pasta & förrätter", secondo:"Varmrätter", dolce:"Efterrätt", antipasto:"Tilltugg", conserve:"Konserver",
    d:["Det här kaffet är tillägnat drömmarna,","den som insjuknat i förundran,","den som suckar i vinden,","den som ser månen och blir rörd,","den som smeker världen,","den som gick vilse och fann sig igen,","de stora själarna,","leenden gjorda i hemlighet,","folket som viskar,","molnen som vinden slår,","ovädren, solen,","dem som älskar varandra utan att veta om det,","våren,","dagen du föddes,","min mamma, och din också.","Tillägnat dig, mig."]
  }
};

const RECIPES = [
  {id:"brasato",s:"INVERNO",m:"GENNAIO",k:"secondo",time:150,
   t:{it:"Brasato al Barolo",en:"Barolo-braised beef",sv:"Brasato al Barolo"},
   i:{it:"Arrosto della vena di Fassone piemontese, una bottiglia di Barolo, aglio, alloro, sale e pepe.",
      en:"Piedmontese Fassone beef roast (vena), one bottle of Barolo, garlic, bay, salt and pepper.",
      sv:"Piemontesisk Fassone-rostbiff, en flaska Barolo, vitlök, lagerblad, salt och peppar."},
   p:{it:"Lasciare marinare il taglio di carne per mezza giornata nel vino. Passare poi alla cottura che deve essere forte all'inizio e poi lenta e bassa per un paio d'ore.",
      en:"Marinate the meat in the wine for half a day. Cook hard at first, then slowly over low heat for a couple of hours.",
      sv:"Marinera köttet i vinet en halv dag. Stek hårt i början, sedan sakta på låg värme i ett par timmar."}},
  {id:"zabaglione",s:"INVERNO",m:"GENNAIO",k:"dolce",time:15,
   t:{it:"Zabaglione",en:"Zabaglione",sv:"Zabaglione"},
   i:{it:"4 tuorli, 4 cucchiai di zucchero, 4 cucchiai di Marsala secco.",
      en:"4 egg yolks, 4 tablespoons sugar, 4 tablespoons dry Marsala.",
      sv:"4 äggulor, 4 msk socker, 4 msk torr Marsala."},
   p:{it:"Sbattere i tuorli con lo zucchero fino a quando diventano una crema chiara. Aggiungere il Marsala e cuocere a fuoco lento fino a bollore. Servire caldo.",
      en:"Beat yolks with sugar until pale and creamy. Add Marsala and cook gently until it just simmers. Serve hot.",
      sv:"Vispa gulor och socker till en ljus kräm. Tillsätt Marsala och sjud sakta. Servera varmt."}},
  {id:"carne-cruda",s:"INVERNO",m:"FEBBRAIO",k:"antipasto",time:20,
   t:{it:"Carne cruda",en:"Piedmontese raw beef",sv:"Carne cruda"},
   i:{it:"500 g di coscia di vitello di Fassone piemontese, uno spicchio d'aglio, olio d'oliva e olio extravergine, sale e pepe.",
      en:"500 g Piedmontese Fassone veal thigh, 1 garlic clove, olive oil and extra-virgin oil, salt and pepper.",
      sv:"500 g piemontesisk Fassone-kalv, 1 vitlöksklyfta, olivolja och extra vergine, salt och peppar."},
   p:{it:"Tagliare al coltello la carne. Pulire l'aglio e schiacciarlo un poco. Condire con sale, pepe e olio metà d'oliva e metà extravergine. Mischiare bene e levare l'aglio prima di servire.",
      en:"Chop the meat with a knife. Crush the garlic lightly. Dress with salt, pepper and half olive oil, half extra-virgin. Mix; remove the garlic before serving.",
      sv:"Hacka köttet med kniv. Krossa vitlöken lätt. Krydda med salt, peppar och hälften olivolja, hälften extra vergine. Ta bort vitlöken före servering."}},
  {id:"gnocchi",s:"INVERNO",m:"FEBBRAIO",k:"primo",time:60,
   t:{it:"Gnocchi di patate",en:"Potato gnocchi",sv:"Potatisgnocchi"},
   i:{it:"1 kg di patate a pasta gialla, 250 g di farina, un uovo.",
      en:"1 kg yellow potatoes, 250 g flour, 1 egg.",
      sv:"1 kg gul potatis, 250 g mjöl, 1 ägg."},
   p:{it:"Lessare le patate, scolare e sbucciarle. Passarle al passaverdure e lasciarle raffreddare. Unire farina e uovo e impastare fino a un impasto liscio. Stendere a striscioline, tagliare pezzetti e formare gli gnocchi col pollice. Cuocere in acqua salata; scolare appena vengono a galla e condire a piacere.",
      en:"Boil, drain and peel the potatoes. Rice them and cool. Add flour and egg; knead smooth. Roll, cut and shape with your thumb. Boil in salted water; drain as they float.",
      sv:"Koka, häll av och skala potatisen. Passera och svalna. Tillsätt mjöl och ägg; knåda slätt. Rulla, skär och forma. Koka i saltat vatten; häll av när de flyter."}},
  {id:"torta-mele",s:"INVERNO",m:"FEBBRAIO",k:"dolce",time:75,
   t:{it:"Torta di mele",en:"Apple tart",sv:"Äppelkaka"},
   i:{it:"250 g di farina, latte q.b., 4–5 mele Renette, zucchero a velo, limone.",
      en:"250 g flour, milk as needed, 4–5 Renette apples, icing sugar, lemon.",
      sv:"250 g mjöl, mjölk efter behov, 4–5 Renette-äpplen, florsocker, citron."},
   p:{it:"Impastare la farina con il latte fino a un impasto liscio ed elastico. Stendere e foderare una tortiera lasciando fuoriuscire la pasta. Disporre le mele a fette, zucchero a velo e scorza di limone. Chiudere con la pasta sporgente, fare un forellino al centro. Cuocere a 170 °C per un'oretta.",
      en:"Knead flour with milk until elastic. Line a tin with overhang. Arrange apple slices, icing sugar and lemon zest. Fold the overhang, poke a centre hole. Bake at 170 °C about an hour.",
      sv:"Knåda mjöl och mjölk elastiskt. Klä en form med överhäng. Lägg äppelskivor, florsocker och citronskal. Vik över, gör ett hål. Grädda 170 °C i cirka en timme."}},
  {id:"insalata-russa",s:"INVERNO",m:"MARZO",k:"antipasto",time:40,
   t:{it:"Insalata russa",en:"Russian salad",sv:"Rysk sallad"},
   i:{it:"Carote, patate, piselli, maionese, tonno.",
      en:"Carrots, potatoes, peas, mayonnaise, tuna.",
      sv:"Morötter, potatis, ärtor, majonnäs, tonfisk."},
   p:{it:"Lessare le verdure e tagliarle a dadini. Condire con maionese (un tuorlo, mezzo succo di limone, olio a filo) e il tonno.",
      en:"Boil and cube the vegetables. Dress with mayonnaise (1 yolk, half a lemon, oil in a stream) and tuna.",
      sv:"Koka och tärna grönsakerna. Blanda med majonnäs (1 gula, halv citron, olja i stril) och tonfisk."}},
  {id:"frittatine",s:"INVERNO",m:"MARZO",k:"antipasto",time:30,
   t:{it:"Frittatine verdi",en:"Little green fritters",sv:"Gröna småomeletter"},
   i:{it:"500 g di spinaci, 6 uova, basilico, menta, sale e pepe.",
      en:"500 g spinach, 6 eggs, basil, mint, salt and pepper.",
      sv:"500 g spenat, 6 ägg, basilika, mynta, salt och peppar."},
   p:{it:"Lessare gli spinaci e frullarli con le erbe e le uova. In padella con olio extravergine formare le frittatine con un cucchiaio e cuocerle.",
      en:"Boil spinach and blend with herbs and eggs. Spoon fritters into extra-virgin oil and cook.",
      sv:"Koka spenaten och mixa med örter och ägg. Forma plättar i extra vergine och stek."}},
  {id:"fritto-misto",s:"INVERNO",m:"MARZO",k:"secondo",time:50,
   t:{it:"Fritto misto",en:"Piedmontese mixed fry",sv:"Fritto misto"},
   i:{it:"200 g salsiccia, 200 g filoni, 200 g cervella, 200 g polpette, 200 g fegato di vitello, 200 g polmone di vitello, 200 g coscia di vitello, semolino dolce, carote.",
      en:"200 g each sausage, sweetbreads, brains, meatballs, veal liver, lung and thigh; sweet semolina; carrots.",
      sv:"200 g vardera korv, kalvbräss, hjärna, köttbullar, kalvlever, lunga och klubba; söt semolina; morötter."},
   p:{it:"Infarinare polpette, fegato, cervella, filoni e polmone. Impanare le cosce e i semolini (latte, semolino, buccia di limone, zucchero). Friggere tutto e servire caldissimo.",
      en:"Flour meatballs, liver, brains, sweetbreads and lung. Bread the veal and sweet semolina. Fry everything and serve very hot.",
      sv:"Mjölä köttbullar, lever, hjärna, bräss och lunga. Panera kalv och semolina. Fritera allt och servera hett."}},
  {id:"uova-ripiene",s:"PRIMAVERA",m:"APRILE",k:"antipasto",time:25,
   t:{it:"Uova ripiene",en:"Stuffed eggs",sv:"Fyllda ägg"},
   i:{it:"Uova, maionese, tonno, capperi, senape.",
      en:"Eggs, mayonnaise, tuna, capers, mustard.",
      sv:"Ägg, majonnäs, tonfisk, kapris, senap."},
   p:{it:"Bollire le uova, sgusciarle e tagliarle a metà. Estrarre i tuorli e mescolarli con maionese, senape, capperi e tonno per il ripieno.",
      en:"Boil, peel and halve the eggs. Mix yolks with mayonnaise, mustard, capers and tuna.",
      sv:"Koka, skala och halvera äggen. Blanda gulorna med majonnäs, senap, kapris och tonfisk."}},
  {id:"tajarin",s:"PRIMAVERA",m:"MAGGIO",k:"primo",time:50,
   t:{it:"Tajarin",en:"Tajarin",sv:"Tajarin"},
   i:{it:"400 g farina 00, 300 g farina di semola, 6 uova intere, 1 cucchiaio di olio extravergine, un pizzico di sale.",
      en:"400 g 00 flour, 300 g semolina flour, 6 whole eggs, 1 tbsp extra-virgin oil, pinch of salt.",
      sv:"400 g 00-mjöl, 300 g semolinamjöl, 6 hela ägg, 1 msk extra vergine, nypa salt."},
   p:{it:"Farina a fontana, unire uova, sale e olio; impastare liscio. Riposare 30 minuti. Tirare sottile e tagliare a listarelle. Cuocere in acqua salata.",
      en:"Make a well, add eggs, salt and oil; knead smooth. Rest 30 minutes. Roll thin, cut ribbons. Cook in salted water.",
      sv:"Gör en brunn, tillsätt ägg, salt och olja; knåda. Vila 30 min. Kavla tunt, skär band. Koka i saltat vatten."}},
  {id:"mousse",s:"PRIMAVERA",m:"MAGGIO",k:"dolce",time:30,
   t:{it:"Mousse al cioccolato fondente",en:"Dark chocolate mousse",sv:"Mörk chokladmousse"},
   i:{it:"200 g cioccolato fondente (55–70 %), 6 uova.",
      en:"200 g dark chocolate (55–70 %), 6 eggs.",
      sv:"200 g mörk choklad (55–70 %), 6 ägg."},
   p:{it:"Sciogliere il cioccolato a bagnomaria. Montare gli albumi a neve e tenere in frigo. Togliere il cioccolato dal fuoco, unire i tuorli uno alla volta, poi gli albumi. Versare in coppette e frigo almeno 3 ore.",
      en:"Melt chocolate over a bain-marie. Whip whites stiff. Off the heat add yolks one by one, fold in whites. Chill at least 3 hours.",
      sv:"Smält chokladen över vattenbad. Vispa vitorna. Ta av värmen, vispa i gulorna, vänd i vitorna. Kyl minst 3 timmar."}},
  {id:"crostata",s:"PRIMAVERA",m:"MAGGIO",k:"dolce",time:55,
   t:{it:"Crostata di mirtilli",en:"Blueberry tart",sv:"Blåbärspaj"},
   i:{it:"250 g farina di grano tenero, 125 g burro, 100 g zucchero, un uovo, scorza di limone, pizzico di sale, un vasetto di confettura di mirtilli.",
      en:"250 g wheat flour, 125 g butter, 100 g sugar, 1 egg, lemon zest, pinch of salt, a jar of blueberry jam.",
      sv:"250 g vetemjöl, 125 g smör, 100 g socker, 1 ägg, citronskal, nypa salt, en burk blåbärssylt."},
   p:{it:"Lavorare burro morbido con zucchero, sale e scorza. Unire l'uovo, poi la farina in fretta. Palla in frigo 30 min. Stendere, foderare una tortiera imburrata, bucherellare. Confettura e 6 strisce di avanzo. 180 °C per circa 25 minuti.",
      en:"Work soft butter with sugar, salt and zest. Add egg, then flour quickly. Chill 30 min. Line a tin, prick, jam and 6 strips. 180 °C about 25 minutes.",
      sv:"Arbeta smör med socker, salt och skal. Tillsätt ägg, sedan mjöl. Kyl 30 min. Klä form, sylt och 6 remsor. 180 °C ca 25 min."}},
  {id:"vitello-tonnato",s:"PRIMAVERA",m:"GIUGNO",k:"antipasto",time:60,
   t:{it:"Vitello tonnato",en:"Vitello tonnato",sv:"Vitello tonnato"},
   i:{it:"½ kg girello, una cipolla, alloro, sale grosso. Per la salsa: 100 g maionese, 3 filetti di acciuga, 3–4 capperi.",
      en:"500 g veal eye of round, 1 onion, bay, coarse salt. Sauce: 100 g mayonnaise, 3 anchovy fillets, 3–4 capers.",
      sv:"500 g kalvytterlår, 1 lök, lagerblad, grovt salt. Sås: 100 g majonnäs, 3 ansjovis, 3–4 kapris."},
   p:{it:"Cuocere il girello 30 minuti a 170 °C coperto di sale grosso, alloro e cipolla a quarti. Raffreddare e frigo alcune ore. Tritare acciughe e capperi, unire la maionese, frigo 30 min. Affettare la carne e nappare con la salsa.",
      en:"Roast the veal 30 min at 170 °C under coarse salt, bay and onion. Cool and chill. Chop anchovies and capers into mayonnaise. Slice and coat.",
      sv:"Stek kalven 30 min i 170 °C under salt, lager och lök. Svalna och kyl. Hacka ansjovis och kapris i majonnäsen. Skiva och täck."}},
  {id:"frittata",s:"PRIMAVERA",m:"GIUGNO",k:"secondo",time:25,
   t:{it:"Frittata di zucchini",en:"Zucchini frittata",sv:"Zucchinifrittata"},
   i:{it:"10 uova, 4–5 zucchine, mezza cipolla, olio extravergine, sale e pepe.",
      en:"10 eggs, 4–5 zucchini, half an onion, extra-virgin oil, salt and pepper.",
      sv:"10 ägg, 4–5 zucchini, halv lök, extra vergine, salt och peppar."},
   p:{it:"Affettare le zucchine e passarle in padella con olio e cipolla. Montare le uova con sale e pepe e versarle sopra. Rigirare almeno una volta col coperchio. Servire fumante.",
      en:"Sauté sliced zucchini with oil and onion. Pour beaten seasoned eggs over. Flip once with a lid. Serve steaming.",
      sv:"Fräs zucchiniskivor med olja och lök. Häll vispade ägg över. Vänd en gång. Servera rykande."}},
  {id:"nonna-pina",s:"PRIMAVERA",m:"GIUGNO",k:"dolce",time:70,
   t:{it:"Torta di Nonna Pina",en:"Grandma Pina’s cake",sv:"Nonna Pinas tårta"},
   i:{it:"700 g pasta frolla, 2 tuorli, 50 g zucchero, 40 g farina, 2 dl latte, 100 g cioccolato fondente.",
      en:"700 g shortcrust, 2 yolks, 50 g sugar, 40 g flour, 200 ml milk, 100 g dark chocolate.",
      sv:"700 g mördeg, 2 gulor, 50 g socker, 40 g mjöl, 2 dl mjölk, 100 g mörk choklad."},
   p:{it:"Grattugiare il cioccolato. Bollire il latte. Montare tuorli e zucchero, unire farina e latte caldo; cuocere dolcissimo finché addensa, poi il cioccolato. Due dischi di frolla: foderare, bucherellare, crema, coprire. 180 °C per circa 30 minuti.",
      en:"Grate chocolate. Boil milk. Whisk yolks and sugar with flour and hot milk until thick; add chocolate. Two pastry discs: line, fill, cover. 180 °C about 30 minutes.",
      sv:"Riv chokladen. Koka mjölken. Vispa gulor och socker med mjöl och varm mjölk tills den tjocknar; tillsätt choklad. Två bottnar: klä, fyll, täck. 180 °C ca 30 min."}},
  {id:"tonno-coniglio",s:"ESTATE",m:"LUGLIO",k:"secondo",time:90,
   t:{it:"Tonno di coniglio",en:"Rabbit ‘tuna’",sv:"Kanin ‘tonfisk’"},
   i:{it:"Un coniglio intero pulito senza fegato, cipolla, carota, tre gambi di sedano, mazzetto di alloro rosmarino e salvia, chiodi di garofano, bacche di ginepro, una testa d'aglio, olio extravergine, sale e pepe in grani.",
      en:"1 whole cleaned rabbit without liver, onion, carrot, 3 celery stalks, bay-rosemary-sage, cloves, juniper, a head of garlic, extra-virgin oil, salt and peppercorns.",
      sv:"1 hel rensad kanin utan lever, lök, morot, 3 selleristjälkar, lager-rosmarin-salvia, nejlikor, enbär, ett vitlökshuvud, extra vergine, salt och pepparkorn."},
   p:{it:"Lessare il coniglio 30 minuti in acqua salata con gli aromi; raffreddare nel brodo. A tocchetti, a strati in un vaso con aglio, salvia, alloro, pepe e un filo d'olio. Marinare un giorno. Servire con valeriana.",
      en:"Simmer rabbit 30 minutes with aromatics; cool in the broth. Layer cubes in a jar with garlic, sage, bay, pepper and oil. Marinate one day. Serve with lamb’s lettuce.",
      sv:"Sjud kaninen 30 min med kryddor; svalna i spadet. Varva i burk med vitlök, salvia, lager, peppar och olja. Marinera ett dygn."}},
  {id:"carpione",s:"ESTATE",m:"AGOSTO",k:"secondo",time:45,
   t:{it:"Carpione",en:"Carpione",sv:"Carpione"},
   i:{it:"6 bistecche di vitello impanate, 6 uova, 1 kg zucchini, 30 polpette, olio extravergine, 5 spicchi d'aglio, salvia, alloro, aceto di vino bianco.",
      en:"6 breaded veal cutlets, 6 eggs, 1 kg zucchini, 30 meatballs, extra-virgin oil, 5 garlic cloves, sage, bay, white wine vinegar.",
      sv:"6 panerade kalvsnitzlar, 6 ägg, 1 kg zucchini, 30 köttbullar, extra vergine, 5 vitlöksklyftor, salvia, lagerblad, vitvinsvinäger."},
   p:{it:"Appassire salvia e aglio in poco olio. Aggiungere abbondante aceto, salare, portare a bollore. Versare ben caldo su bistecche, zucchini, uova e polpette. Raffreddare e frigorifero.",
      en:"Wilt sage and garlic in oil. Add plenty of vinegar, salt, boil. Pour hot over cutlets, zucchini, eggs and meatballs. Cool and refrigerate.",
      sv:"Fräs salvia och vitlök. Tillsätt vinäger, salta, koka upp. Häll hett över snitzlar, zucchini, ägg och köttbullar. Kyl."}},
  {id:"bagnetto",s:"ESTATE",m:"AGOSTO",k:"antipasto",time:15,
   t:{it:"Bagnetto verde",en:"Green sauce",sv:"Grön sås"},
   i:{it:"Una grossa manciata di prezzemolo, una decina di capperi, 2 acciughe, 1 spicchio d'aglio, mollica di pane imbevuta di aceto e strizzata, 1 tuorlo sodo.",
      en:"A large handful of parsley, about 10 capers, 2 anchovies, 1 garlic clove, vinegar-soaked bread, 1 hard-boiled yolk.",
      sv:"En stor näve persilja, cirka 10 kapris, 2 ansjovis, 1 vitlöksklyfta, vinägerblötlagt bröd, 1 kokt äggula."},
   p:{it:"Tritare tutto. Aggiungere olio extravergine fino a una salsa consistente e omogenea.",
      en:"Chop everything. Stir in extra-virgin oil until thick and even.",
      sv:"Hacka allt. Rör i extra vergine tills såsen är tjock."}},
  {id:"conserva",s:"ESTATE",m:"AGOSTO",k:"conserve",time:180,
   t:{it:"Conserva di pomodoro",en:"Tomato preserve",sv:"Tomatsås på burk"},
   i:{it:"5 kg pomodori, 3 carote, 3 gambi di sedano, 3 cipolle, 3 spicchi d'aglio, un mazzo di basilico.",
      en:"5 kg tomatoes, 3 carrots, 3 celery stalks, 3 onions, 3 garlic cloves, a bunch of basil.",
      sv:"5 kg tomater, 3 morötter, 3 selleristjälkar, 3 lökar, 3 vitlöksklyftor, en knippe basilika."},
   p:{it:"Bollire i pomodori, unire le verdure e cuocere alcune ore. Passare e rimettere sul fuoco. Sale e un pizzico di zucchero. Barattoli; sterilizzare 30 minuti a 100 °C.",
      en:"Boil tomatoes with vegetables several hours. Mill and reduce. Salt and a pinch of sugar. Jars; sterilize 30 minutes at 100 °C.",
      sv:"Koka tomater och grönsaker flera timmar. Passera och koka in. Salt och en nypa socker. Sterilisera 30 min vid 100 °C."}},
  {id:"giardiniera",s:"ESTATE",m:"SETTEMBRE",k:"conserve",time:60,
   t:{it:"Giardiniera",en:"Giardiniera",sv:"Giardiniera"},
   i:{it:"1 kg per qualità: pomodori maturi, carote, cipolline, zucchini, peperoni gialli e rossi, sedano, fagiolini, cavolfiore; 1 l aceto di vino bianco, 3 cucchiai zucchero, sale e olio extravergine.",
      en:"1 kg of each vegetable listed; 1 l white wine vinegar, 3 tbsp sugar, salt and extra-virgin oil.",
      sv:"1 kg av varje grönsak; 1 l vitvinsvinäger, 3 msk socker, salt och extra vergine."},
   p:{it:"Pulire e tagliare (cipolle intere). Cuocere nel pomodoro partendo da carote, fagiolini e sedano; poi cipolline, cavolfiore e peperoni. Aceto, zucchero, olio, sale; 3 minuti. Raffreddare nei vasetti sterilizzati.",
      en:"Cut vegetables (onions whole). Cook in tomato starting with carrots, beans and celery. Add vinegar, sugar, oil, salt; 3 minutes. Jar when cool.",
      sv:"Skär grönsakerna (löken hel). Koka i tomat med morötter först. Vinäger, socker, olja, salt; 3 min. Burka när det svalnat."}},
  {id:"meliga",s:"ESTATE",m:"SETTEMBRE",k:"dolce",time:40,
   t:{it:"Paste di meliga",en:"Meliga biscuits",sv:"Meliga-kakor"},
   i:{it:"200 g farina di mais, 200 g farina 00, 1 uovo, 1 tuorlo, 200 g burro, 160 g zucchero, pizzico di sale.",
      en:"200 g cornmeal, 200 g 00 flour, 1 egg, 1 yolk, 200 g butter, 160 g sugar, pinch of salt.",
      sv:"200 g majsmjöl, 200 g 00-mjöl, 1 ägg, 1 gula, 200 g smör, 160 g socker, nypa salt."},
   p:{it:"Mescolare farine, zucchero e sale. Unire burro morbido, uovo e tuorlo. Frigo 30 min. Sfoglia da ½ cm, cuoricini. 175 °C per una decina di minuti.",
      en:"Mix flours, sugar and salt. Add soft butter, egg and yolk. Chill 30 min. Roll ½ cm, cut hearts. 175 °C about 10 minutes.",
      sv:"Blanda mjöl, socker och salt. Tillsätt smör, ägg och gula. Kyl 30 min. Kavla ½ cm, hjärtan. 175 °C ca 10 min."}},
  {id:"nocciole",s:"ESTATE",m:"SETTEMBRE",k:"dolce",time:45,
   t:{it:"Torta di nocciole",en:"Hazelnut cake",sv:"Hasselnötskaka"},
   i:{it:"200 g nocciole tostate, 4 uova, 150 g zucchero.",
      en:"200 g toasted hazelnuts, 4 eggs, 150 g sugar.",
      sv:"200 g rostade hasselnötter, 4 ägg, 150 g socker."},
   p:{it:"Montare i tuorli con lo zucchero. Tritare le nocciole. Albumi a neve. Unire crema e nocciole, poi i bianchi dal basso. Stampo imburrato. 170 °C per una trentina di minuti.",
      en:"Beat yolks with sugar. Grind nuts. Whip whites. Combine and fold. Butter a tin. 170 °C about 30 minutes.",
      sv:"Vispa gulor och socker. Mal nötter. Vispa vitor. Blanda och vänd. Smord form. 170 °C ca 30 min."}},
  {id:"ragu",s:"AUTUNNO",m:"OTTOBRE",k:"primo",time:45,
   t:{it:"Ragù",en:"Ragù",sv:"Ragù"},
   i:{it:"300 g macinato di vitello, 300 g salsiccia, ½ kg passata di pomodoro, due spicchi d'aglio, olio extravergine, sale, mezzo bicchiere di vino bianco.",
      en:"300 g ground veal, 300 g sausage, 500 g tomato passata, 2 garlic cloves, extra-virgin oil, salt, half a glass of white wine.",
      sv:"300 g malet kalvkött, 300 g korv, 500 g passata, 2 vitlöksklyftor, extra vergine, salt, ett halvt glas vitt vin."},
   p:{it:"Soffriggere l'aglio. Aggiungere carne e salsiccia, sfumare col vino, unire la passata. 30 minuti a fuoco basso. Sale.",
      en:"Sauté garlic. Add meats, deglaze with wine, add passata. 30 minutes on low heat. Salt.",
      sv:"Fräs vitlök. Tillsätt kött, släck med vin, häll i passata. 30 min på låg värme."}},
  {id:"risotto",s:"AUTUNNO",m:"OTTOBRE",k:"primo",time:35,
   t:{it:"Risotto con salsiccia",en:"Sausage risotto",sv:"Korvrisotto"},
   i:{it:"300 g Carnaroli, uno scalogno, 300 g salsiccia, mezzo bicchiere di vino bianco, sale, olio extravergine, 1 l brodo di verdure.",
      en:"300 g Carnaroli, 1 shallot, 300 g sausage, half a glass of white wine, salt, extra-virgin oil, 1 l vegetable broth.",
      sv:"300 g Carnaroli, 1 schalottenlök, 300 g korv, ett halvt glas vitt vin, salt, extra vergine, 1 l grönsaksbuljong."},
   p:{it:"Soffriggere lo scalogno. Unire salsiccia e riso, tostare. Sfumare col vino e aggiungere il brodo poco alla volta. Mantecare con una noce di burro.",
      en:"Sauté shallot. Add sausage and rice; toast. Deglaze with wine and add broth little by little. Finish with butter.",
      sv:"Fräs schalotten. Tillsätt korv och ris; rosta. Släck med vin och häll buljong lite i taget. Avsluta med smör."}},
  {id:"tiramisu",s:"AUTUNNO",m:"OTTOBRE",k:"dolce",time:25,
   t:{it:"Tiramisù",en:"Tiramisu",sv:"Tiramisù"},
   i:{it:"250 g mascarpone, 3 tuorli, un pacco di Pavesini, 150 g zucchero, una tazza capiente di caffè.",
      en:"250 g mascarpone, 3 yolks, a pack of Pavesini, 150 g sugar, a large cup of coffee.",
      sv:"250 g mascarpone, 3 gulor, ett paket Pavesini, 150 g socker, en stor kopp kaffe."},
   p:{it:"Montare uova e zucchero, unire il mascarpone. Alternare Pavesini imbevuti e crema. Cacao amaro sopra. Frigorifero.",
      en:"Beat yolks and sugar, fold in mascarpone. Alternate coffee-dipped Pavesini and cream. Dust with cocoa. Chill.",
      sv:"Vispa gulor och socker, vänd i mascarpone. Varva kaffedoppade Pavesini och kräm. Pudra kakao. Kyl."}},
  {id:"bagna-cauda",s:"AUTUNNO",m:"NOVEMBRE",k:"antipasto",time:50,
   t:{it:"Bagna cauda",en:"Bagna cauda",sv:"Bagna cauda"},
   i:{it:"12 teste d'aglio, 6 bicchieri di olio extravergine, 600 g acciughe rosse di Spagna. Crude: cardi, gobbi, topinambur, cuori di cavolo, indivia, scarola, peperoni, cipollotti. Cotte: patate, barbabietole, cipolle al forno, zucca fritta, peperoni arrostiti.",
      en:"12 heads of garlic, 6 glasses extra-virgin oil, 600 g red Spanish anchovies, plus raw and cooked vegetables for dipping.",
      sv:"12 vitlökshuvuden, 6 glas extra vergine, 600 g röda spanska ansjovis, plus grönsaker att doppa."},
   p:{it:"Aglio senza germoglio in tegame di coccio con un bicchiere d'olio a fuoco bassissimo. Acciughe dissalate, rimestare. Coprire col resto dell'olio; mezz'ora senza friggere. Nei fujot, con le verdure. Alla fine lo ‘spesso’ con un uovo strapazzato.",
      en:"Cook sliced garlic in earthenware with one glass of oil on the lowest heat. Add rinsed anchovies. Cover with remaining oil; 30 minutes without frying. Serve in fujot with vegetables.",
      sv:"Koka skivad vitlök i lergods med ett glas olja på lägsta värme. Tillsätt sköljd ansjovis. Täck med olja; 30 min utan att steka. Servera med grönsaker."}},
  {id:"ceci",s:"AUTUNNO",m:"NOVEMBRE",k:"primo",time:40,
   t:{it:"Vellutata di ceci",en:"Chickpea velouté",sv:"Kikärtssoppa"},
   i:{it:"350 g ceci, mezza cipolla, una carota, un gambo di sedano, sale e olio extravergine.",
      en:"350 g chickpeas, half an onion, 1 carrot, 1 celery stalk, salt and extra-virgin oil.",
      sv:"350 g kikärter, halv lök, 1 morot, 1 selleristjälk, salt och extra vergine."},
   p:{it:"Ammollo 12 ore. Cipolla, carota e sedano in olio un paio di minuti. Ceci, acqua e sale; 20 minuti, poi frullare. Rosmarino e pancetta affumicata.",
      en:"Soak 12 hours. Sauté onion, carrot and celery. Add chickpeas, water and salt; 20 minutes, blend. Rosemary and smoked pancetta.",
      sv:"Blötlägg 12 timmar. Fräs lök, morot och selleri. Tillsätt kikärter, vatten och salt; 20 min, mixa. Rosmarin och rökt pancetta."}},
  {id:"mon",s:"AUTUNNO",m:"NOVEMBRE",k:"dolce",time:25,
   t:{it:"Mon",en:"Mon",sv:"Mon"},
   i:{it:"350 g biscotti tipo Novellini, caffè, 100 g burro, 100 g zucchero a velo, 2 tuorli, 30 g cacao amaro.",
      en:"350 g Novellini-style biscuits, coffee, 100 g butter, 100 g icing sugar, 2 yolks, 30 g cocoa.",
      sv:"350 g Novellini-kex, kaffe, 100 g smör, 100 g florsocker, 2 gulor, 30 g kakao."},
   p:{it:"Montare burro, zucchero a velo, cacao, una tazzina di caffè ristretto e i tuorli. Strati di biscotti imbevuti e crema. Crema e cacao in superficie. Frigorifero.",
      en:"Whip butter, icing sugar, cocoa, a small strong coffee and the yolks. Layer dipped biscuits and cream. Chill.",
      sv:"Vispa smör, florsocker, kakao, en liten stark kaffe och gulorna. Varva doppade kex och kräm. Kyl."}},
  {id:"agnolotti",s:"AUTUNNO",m:"DICEMBRE",k:"primo",time:120,
   t:{it:"Agnolotti",en:"Agnolotti del plin",sv:"Agnolotti"},
   i:{it:"Pasta: 1 kg farina 00, 5 tuorli e 2 uova intere, acqua tiepida q.b., sale. Ripieno: 1 kg arrosto di vitello, 300 g coniglio arrosto, 200 g salsiccia, 300 g fesa di vitello, prezzemolo, 1 spicchio d'aglio, 1 grossa scarola, olio extravergine, sale, pepe, parmigiano.",
      en:"Pasta: 1 kg 00 flour, 5 yolks + 2 whole eggs, water, salt. Filling: roast veal, roast rabbit, sausage, veal rump, parsley, garlic, escarole, oil, Parmesan.",
      sv:"Pasta: 1 kg 00-mjöl, 5 gulor + 2 ägg, vatten, salt. Fyllning: stekt kalv, kanin, korv, persilja, vitlök, escarole, parmesan."},
   p:{it:"Pasta all'uovo elastica. Sfoglia sottile, agnolotti con la rotella. Tritare carni e verdura; unire i 5 albumi avanzati, parmigiano, sale e pepe.",
      en:"Make elastic egg pasta. Roll thin and form agnolotti. Grind meats and greens; add leftover whites, Parmesan, salt and pepper.",
      sv:"Gör elastisk äggpasta. Kavla tunt och forma agnolotti. Mala fyllningen; tillsätt vitor, parmesan, salt och peppar."}},
  {id:"bollito",s:"AUTUNNO",m:"DICEMBRE",k:"secondo",time:180,
   t:{it:"Bollito",en:"Bollito misto",sv:"Bollito misto"},
   i:{it:"1,5 kg muscolo di manzo o punta, 1 kg lingua di vitello, 1,5 kg testina di vitello, 2 cotechini, 1,5 kg scaramella, sedano, carote, cipolle, sale.",
      en:"1.5 kg beef, 1 kg veal tongue, 1.5 kg veal head, 2 cotechini, 1.5 kg belly, celery, carrots, onions, salt.",
      sv:"1,5 kg nötkött, 1 kg kalvtunga, 1,5 kg kalvhuvud, 2 cotechino, 1,5 kg sidfläsk, selleri, morötter, lök, salt."},
   p:{it:"Acqua, sale e verdure a bollore; il manzo circa 2 ore. A parte: testina 2 ore, cotechini forati 30 min, lingua e scaramella un'ora. Vassoio e salse.",
      en:"Boil salted water with vegetables; beef about 2 hours. Separately cook the other meats. Serve on a platter with sauces.",
      sv:"Koka saltat vatten med grönsaker; nötköttet ca 2 tim. Koka övriga kött separat. Servera med såser."}},
  {id:"bonet",s:"AUTUNNO",m:"DICEMBRE",k:"dolce",time:60,
   t:{it:"Bonet",en:"Bonet",sv:"Bonet"},
   i:{it:"8 uova intere, 8 cucchiai zucchero, 4 cucchiai cacao, 1 l latte, 250 g amaretti, ½ bicchierino di Marsala.",
      en:"8 whole eggs, 8 tbsp sugar, 4 tbsp cocoa, 1 l milk, 250 g amaretti, ½ small glass Marsala.",
      sv:"8 hela ägg, 8 msk socker, 4 msk kakao, 1 l mjölk, 250 g amaretti, ½ litet glas Marsala."},
   p:{it:"Caramellare lo stampo. Bollire il latte con gli amaretti. Sbattere uova e zucchero, unire cacao e Marsala, versare. Bagnomaria in forno a 180 °C per 40 minuti. Raffreddare in frigo.",
      en:"Caramelize the mould. Boil milk with amaretti. Beat eggs and sugar, add cocoa and Marsala. Bain-marie at 180 °C for 40 minutes. Chill.",
      sv:"Kola formen. Koka mjölk med amaretti. Vispa ägg och socker, tillsätt kakao och Marsala. Vattenbad 180 °C i 40 min. Kyl."}}
];
